name: Rust CICD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup rustfmt and clippy
      shell: bash
      run: |
        rustup component add rustfmt clippy
    - name: Run clippy check
      shell: bash
      run: |
        cargo clippy --all-features
    - name: Run rustfmt check
      shell: bash
      run: |
        cargo fmt --all -- --check
    - name: Test
      shell: bash
      run: |
        cargo test --all-features
    - name: Release build
      run: |
        cargo build --release --all-features
    - name: Publish
      if: ${{ contains(github.event.head_commit.message, 'release') }}
      run: cargo publish
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}